#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.7a
# In conjunction with Tcl version 8.6
#    Jan 16, 2017 07:03:44 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import WCPE_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    WCPE_support.set_Tk_var()
    top = WCPE__Now_Playing (root)
    WCPE_support.init(root, top)
    root.mainloop()

w = None
def create_WCPE__Now_Playing(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    WCPE_support.set_Tk_var()
    top = WCPE__Now_Playing (w)
    WCPE_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_WCPE__Now_Playing():
    global w
    w.destroy()
    w = None


class WCPE__Now_Playing:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 
        font11 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans Mono} -size 14 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font=font9)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("811x632+584+166")
        top.title("WCPE  Now Playing")
        top.configure(background="wheat")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")
        top.bind('<Control-Key-q>',lambda e:WCPE_support.c_quit(e))



        self.Scrolledtext1 = ScrolledText(top)
        self.Scrolledtext1.place(relx=0.01, rely=0.3, relheight=0.6
                , relwidth=0.97)
        self.Scrolledtext1.configure(background="white")
        self.Scrolledtext1.configure(font=font9)
        self.Scrolledtext1.configure(highlightbackground="wheat")
        self.Scrolledtext1.configure(insertborderwidth="3")
        self.Scrolledtext1.configure(selectbackground="#ddc8a1")
        self.Scrolledtext1.configure(width=10)
        self.Scrolledtext1.configure(wrap=NONE)

        self.TSizegrip1 = ttk.Sizegrip(top)
        self.TSizegrip1.place(anchor=SE, relx=1.0, rely=1.0)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.44, rely=0.92, height=31, width=59)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background="wheat")
        self.Button1.configure(command=WCPE_support.quit)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font11)
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Quit''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.05, rely=0.02, height=23, width=162)
        self.Label1.configure(activebackground="#ffffcd")
        self.Label1.configure(background="#f5f5dedeb3b3")
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font=font11)
        self.Label1.configure(highlightbackground="wheat")
        self.Label1.configure(text='''Current Local Time:''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.05, rely=0.06, height=23, width=91)
        self.Label2.configure(activebackground="#ffffcd")
        self.Label2.configure(background="wheat")
        self.Label2.configure(disabledforeground="#b8a786")
        self.Label2.configure(font=font11)
        self.Label2.configure(highlightbackground="wheat")
        self.Label2.configure(text='''Composer:''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.05, rely=0.16, height=23, width=100)
        self.Label3.configure(activebackground="#ffffcd")
        self.Label3.configure(background="wheat")
        self.Label3.configure(disabledforeground="#b8a786")
        self.Label3.configure(font=font11)
        self.Label3.configure(highlightbackground="wheat")
        self.Label3.configure(text='''Performers:''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.05, rely=0.11, height=23, width=43)
        self.Label4.configure(activebackground="#ffffcd")
        self.Label4.configure(background="wheat")
        self.Label4.configure(disabledforeground="#b8a786")
        self.Label4.configure(font=font11)
        self.Label4.configure(highlightbackground="wheat")
        self.Label4.configure(text='''Title:''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.05, rely=0.21, height=23, width=93)
        self.Label5.configure(activebackground="#ffffcd")
        self.Label5.configure(background="wheat")
        self.Label5.configure(disabledforeground="#b8a786")
        self.Label5.configure(font=font11)
        self.Label5.configure(highlightbackground="wheat")
        self.Label5.configure(text='''Start Time:''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.32, rely=0.02, height=27, width=223)
        self.Label6.configure(activebackground="#ffffcd")
        self.Label6.configure(anchor=W)
        self.Label6.configure(background="wheat")
        self.Label6.configure(disabledforeground="#b8a786")
        self.Label6.configure(font=font11)
        self.Label6.configure(highlightbackground="wheat")
        self.Label6.configure(justify=LEFT)
        self.Label6.configure(text='''Label''')
        self.Label6.configure(textvariable=WCPE_support.time_current)

        self.Label7 = Label(top)
        self.Label7.place(relx=0.32, rely=0.06, height=27, width=233)
        self.Label7.configure(activebackground="#ffffcd")
        self.Label7.configure(anchor=W)
        self.Label7.configure(background="wheat")
        self.Label7.configure(disabledforeground="#b8a786")
        self.Label7.configure(font=font11)
        self.Label7.configure(highlightbackground="wheat")
        self.Label7.configure(justify=LEFT)
        self.Label7.configure(text='''Label''')
        self.Label7.configure(textvariable=WCPE_support.composer)

        self.Label8 = Label(top)
        self.Label8.place(relx=0.32, rely=0.11, height=27, width=483)
        self.Label8.configure(activebackground="#ffffcd")
        self.Label8.configure(anchor=W)
        self.Label8.configure(background="wheat")
        self.Label8.configure(disabledforeground="#b8a786")
        self.Label8.configure(font=font11)
        self.Label8.configure(highlightbackground="wheat")
        self.Label8.configure(justify=LEFT)
        self.Label8.configure(text='''Label''')
        self.Label8.configure(textvariable=WCPE_support.title)

        self.Label9 = Label(top)
        self.Label9.place(relx=0.32, rely=0.16, height=27, width=483)
        self.Label9.configure(activebackground="#ffffcd")
        self.Label9.configure(anchor=W)
        self.Label9.configure(background="wheat")
        self.Label9.configure(disabledforeground="#b8a786")
        self.Label9.configure(font=font11)
        self.Label9.configure(highlightbackground="#f5f5dedeb3b3")
        self.Label9.configure(justify=LEFT)
        self.Label9.configure(text='''Label''')
        self.Label9.configure(textvariable=WCPE_support.performers)

        self.Label10 = Label(top)
        self.Label10.place(relx=0.32, rely=0.21, height=27, width=483)
        self.Label10.configure(activebackground="#ffffcd")
        self.Label10.configure(anchor=W)
        self.Label10.configure(background="wheat")
        self.Label10.configure(disabledforeground="#b8a786")
        self.Label10.configure(font=font11)
        self.Label10.configure(highlightbackground="wheat")
        self.Label10.configure(justify=LEFT)
        self.Label10.configure(text='''Label''')
        self.Label10.configure(textvariable=WCPE_support.start_time)





# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

if __name__ == '__main__':
    vp_start_gui()



