#############################################################################
# Generated by PAGE version 4.8.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #f5deb3
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m39
    set site_3_0 $base.m39
    set site_4_0 $site_3_0.men41
    set site_3_0 $base.m39
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#
    menu .pop43 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#f5deb3} -font TkMenuFont -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop43" "Popupmenu1" vTcl:WidgetProc "" 1
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#f5deb3} -command lambda:use_xv(event) \
        -font {{DejaVu Sans Mono} 12} -foreground {#000000} \
        -label {Display using xv} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#f5deb3} -command lambda:call_geeqie(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Display using Geeqie} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#f5deb3} -command add_to_archive \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Add to Archive} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#f5deb3} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Modify Attributes} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#f5deb3} -command lambda:show_description(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Display Description} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#f5deb3} -command lambda:show_exif(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Display Exif} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command lambda:duplicate_image(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Duplicate Image} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command lambda:export(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Export 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command lambda:delete_image(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Delete 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command lambda:call_gimp(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Modify using Gimp} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command {lambda:rotate_images(event, 270)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Rotate Clockwise} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command {lambda:rotate_images(event, 90)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Rotate CtrClockwise} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command clear_selected_images \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Null-Clear Selection} 
    .pop43 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command quit \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 
    menu .pop37 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#f5deb3} -font TkMenuFont -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop37" "Popupmenu2" vTcl:WidgetProc "" 1
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:use_xv(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Display using xv} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:call_geeqie(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Display using Geeqie} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:add_to_archive(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Add to Archive} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:show_exif(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Show Exif} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:duplicate_image(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Duplicate Image} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:call_gimp(event) \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Modify using Gimp} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {lambda:rotate_images(event, 270)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Rotate Clockwise} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {lambda:rotate_images(event, 90)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Rotate CtrClockwise} 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:clear_selected_images \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Null-ClearSelection 
    .pop37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command quit \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m39" -background {#f5deb3} -highlightbackground {#f5deb3} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x460+658+160
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "FotoAlbum"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bind $top <Control-Key-KP_Add> {
        lambda e: zoom('in')
    }
    bind $top <Control-Key-KP_Subtract> {
        lambda e: zoom('out')
    }
    bind $top <Control-Key-a> {
        lambda e: display_dir('arc')
    }
    bind $top <Control-Key-i> {
        lambda e: display_dir('inc')
    }
    bind $top <Control-Key-minus> {
        lambda e: zoom_out()
    }
    bind $top <Control-Key-p> {
        lambda e: popup1(e)
    }
    bind $top <Control-Key-q> {
        lambda e: quit()
    }
    bind $top <Control-Key-r> {
        lambda e: refresh()
    }
    bind $top <Control-Key-s> {
        lambda e: view_archive()
    }
    bind $top <Control-Key-t> {
        lambda e: toggle_file_name()
    }
    bind $top <Key-Shift_L><Control-Key-plus> {
        lambda e: zoom_in()
    }
    bind $top <Key-Shift_R><Control-Key-plus> {
        lambda e : zoom_in()
    }
    vTcl::widgets::ttk::custom::CreateCmd $top.cus38 \
        -background {#f5deb3} -height 75 -highlightbackground {#f5deb3} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.cus38" "Custom1" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m39 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -font TkDefaultFont -foreground {#000000} -tearoff 0 
    $top.m39 add cascade \
        -menu "$top.m39.men40" -activebackground {#f4bcb2} \
        -activeforeground {#111111} -background wheat -command {} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Photos 
    set site_3_0 $top.m39
    menu $site_3_0.men40 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#f5deb3} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-S -background {#d9d9d9} -command {#view_archive} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Search Archive} 
    $site_3_0.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-I -background {#d9d9d9} \
        -command {#lambda:display_dir('inc')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Incoming directory} 
    $site_3_0.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-A -background {#d9d9d9} \
        -command lambda:display_dir('arc') \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {View Archive directory} 
    $site_3_0.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-q -background {#d9d9d9} -command {#quit} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 
    $top.m39 add cascade \
        -menu "$top.m39.men41" -activebackground {#f4bcb2} \
        -activeforeground {#111111} -background wheat -command {} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Actions 
    set site_3_0 $top.m39
    menu $site_3_0.men41 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#f5deb3} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men41 add cascade \
        -menu "$site_3_0.men41.men42" -activebackground {#f4bcb2} \
        -activeforeground {#111111} -accelerator {} -background {#d9d9d9} \
        -command {} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Zoom 
    set site_4_0 $site_3_0.men41
    menu $site_4_0.men42 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#f5deb3} -font TkMenuFont -foreground black -tearoff 0 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-+ -background {#d9d9d9} \
        -command {#lambda:zoom('in')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom In} 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-- -background {#d9d9d9} \
        -command {#lambda:zoom('out')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom Out} 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} \
        -command {#lambda:zoom('default')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Default Size} 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:zoom(300)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 300x300 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:zoom(400)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 400x400 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:zoom(400)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 500x500 
    $site_4_0.men42 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:zoom(600)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 600x600 
    $site_3_0.men41 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-R -background {#d9d9d9} -command {#refresh} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Refresh 
    $site_3_0.men41 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#display_attributes} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Display Attributes} 
    $site_3_0.men41 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-T -background {#d9d9d9} \
        -command {#toggle_file_name} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Toggle File Name} 
    $top.m39 add cascade \
        -menu "$top.m39.men37" -activebackground {#f4bcb2} \
        -activeforeground {#111111} -background wheat -command {} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Zoom 
    set site_3_0 $top.m39
    menu $site_3_0.men37 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#f5deb3} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator Cntrl-+ -background {#d9d9d9} \
        -command {#lambda:zoom('in')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom In} 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator cntrl-- -background {#d9d9d9} \
        -command {#lambda:zoom('out')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom Out} 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} \
        -command {#lambda:zoom('default')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Default Size} 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:Zoom(300)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 300x300 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} \
        -command {#lambda:zoom(400)     } \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 400x400 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:zoom(500)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 500x500 
    $site_3_0.men37 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -accelerator {} -background {#d9d9d9} -command {#lambda:zoom(600)} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label 600x600 
    $top.m39 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command {#quit} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 
    button $top.but37 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#f5deb3} -command quit -disabledforeground {#b8a786} \
        -font font10 -foreground {#000000} -highlightbackground {#f5deb3} \
        -highlightcolor black -text Quit 
    vTcl:DefineAlias "$top.but37" "Button1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.cus38 \
        -in $top -x 0 -y 0 -width 600 -relwidth 0 -height 380 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but37 \
        -in $top -x 250 -y 410 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

