#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.7a
# In conjunction with Tcl version 8.6
#    Jan 10, 2017 10:25:51 PM
#    Jan 10, 2017 11:29:00 PM


import sys
import os

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1





def zoom(p1):
    print('fa_support.zoom')
    sys.stdout.flush()


def add_to_archive():
    print('fa_support.add_to_archive')
    sys.stdout.flush()

def clear_selected_images():
    print('fa_support.clear_selected_images')
    sys.stdout.flush()

def display_attributes():
    print('fa_support.display_attributes')
    sys.stdout.flush()

def display_dir(p1):
    print('fa_support.display_dir')
    sys.stdout.flush()

def zoom(p1):
    print('fa_support.zoom')
    sys.stdout.flush()

def quit():
    print('fa_support.quit')
    sys.stdout.flush()
    sys.exit()

def refresh():
    print('fa_support.refresh')
    sys.stdout.flush()

def toggle_file_name():
    print('fa_support.toggle_file_name')
    sys.stdout.flush()
  

def view_archive():
    print('fa_support.view_archive')
    sys.stdout.flush()

def zoom_in(p1):
    print('fa_support.zoom_in')
    sys.stdout.flush()

def zoom_out(p1):
    print('fa_support.zoom_out')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

# Placeholder to be replace by user definition of Custom.
Custom = Frame

if __name__ == '__main__':
    import fa
    fa.vp_start_gui()





