#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.7a
# In conjunction with Tcl version 8.6
#    Jan 16, 2017 06:49:14 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import canvasc_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    canvasc_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    canvasc_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 

        top.geometry("600x450+-9+69")
        top.title("New Toplevel 1")
        top.configure(highlightbackground="#f5deb3")
        top.configure(highlightcolor="black")



        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.13, rely=0.09, relheight=0.6, relwidth=0.64)
        self.Canvas1.configure(background="white")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#f5deb3")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=378)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.65, rely=0.84, height=26, width=67)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(command=canvasc_support.quit)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(highlightbackground="#f5deb3")
        self.Button1.configure(text='''Quit''')
        self.Button1.configure(width=57)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.47, rely=0.84, height=26, width=67)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(command=canvasc_support.draw)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(highlightbackground="#f5deb3")
        self.Button2.configure(text='''Draw''')
        self.Button2.configure(width=57)






if __name__ == '__main__':
    vp_start_gui()



