#############################################################################
# Generated by PAGE version 4.8.8.1
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.scr35
    set site_3_0 $base.scr37
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background wheat -highlightbackground wheat -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 811x685+195+72
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Now Playing"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bind $top <Control-Key-q> {
        lambda e: c_quit(e)
    }
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr35 \
        -background {#f5deb3} -height 75 -highlightbackground {#f5deb3} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr35" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.scr35 <ButtonRelease-1> {
        lambda e: selection(e)
    }

    $top.scr35.01 configure -background white \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground wheat \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #ddc8a1 \
        -selectforeground black \
        -width 10 \
        -wrap none
    ttk::style configure TSizegrip -background wheat
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi36 \
        -cursor bottom_right_corner 
    vTcl:DefineAlias "$top.tSi36" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but34 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command previous -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text {Previous CD's} 
    vTcl:DefineAlias "$top.but34" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab38 \
        -activebackground {#ffffcd} -activeforeground black -background wheat \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -text Title: 
    vTcl:DefineAlias "$top.lab38" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -activebackground {#ffffcd} -activeforeground black -background wheat \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -text {Start Time:} 
    vTcl:DefineAlias "$top.lab40" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#ffffcd} -activeforeground black -anchor w \
        -background wheat -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -justify left -text Label \
        -textvariable start_time 
    vTcl:DefineAlias "$top.lab43" "Label10" vTcl:WidgetProc "Toplevel1" 1
    button $top.cpd37 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command new_album -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text {New Album} 
    vTcl:DefineAlias "$top.cpd37" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.cpd38 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command quit -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Quit 
    vTcl:DefineAlias "$top.cpd38" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but37 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command repeat_cd -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text {Repeat CD} 
    vTcl:DefineAlias "$top.but37" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but38 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command cont -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Continue 
    vTcl:DefineAlias "$top.but38" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but39 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command stop -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Stop 
    vTcl:DefineAlias "$top.but39" "Button6" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr37 \
        -background {#f5deb3} -height 75 -highlightbackground {#f5deb3} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr37" "Scrolledtext2" vTcl:WidgetProc "Toplevel1" 1

    $top.scr37.01 configure -background white \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground wheat \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #ddc8a1 \
        -selectforeground black \
        -width 10 \
        -wrap word
    button $top.but40 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command search -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Search 
    vTcl:DefineAlias "$top.but40" "Button7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent41 \
        -background white -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground {#f5deb3} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#ddc8a1} -selectforeground black \
        -textvariable criteria 
    vTcl:DefineAlias "$top.ent41" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.ent41 <Key-Return> {
        lambda e: search()
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.scr35 \
        -in $top -x 10 -y 130 -width 786 -relwidth 0 -height 332 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSi36 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 
    place $top.but34 \
        -in $top -x 340 -y 490 -width 165 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab38 \
        -in $top -x 40 -y 30 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 40 -y 90 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 260 -y 90 -width 483 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.cpd37 \
        -in $top -x 60 -y 560 -width 165 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode inside 
    place $top.cpd38 \
        -in $top -x 600 -y 560 -width 165 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode inside 
    place $top.but37 \
        -in $top -x 60 -y 490 -width 165 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but38 \
        -in $top -x 340 -y 560 -width 165 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but39 \
        -in $top -x 600 -y 490 -width 165 -height 51 -anchor nw \
        -bordermode ignore 
    place $top.scr37 \
        -in $top -x 160 -y 10 -width 538 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 170 -y 630 -anchor nw -bordermode ignore 
    place $top.ent41 \
        -in $top -x 360 -y 630 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

