#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.7a
# In conjunction with Tcl version 8.6
#    Jan 09, 2017 10:05:09 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import standard_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    standard_support.set_Tk_var()
    top = New_Toplevel_1 (root)
    standard_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    standard_support.set_Tk_var()
    top = New_Toplevel_1 (w)
    standard_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 
        font10 = "-family {DejaVu Sans} -size 14 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x782+650+150")
        top.title("New Toplevel 1")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")



        self.Message1 = Message(top)
        self.Message1.place(relx=0.15, rely=0.04, relheight=0.03, relwidth=0.14)
        self.Message1.configure(font=font11)
        self.Message1.configure(highlightbackground="wheat")
        self.Message1.configure(text='''Message''')
        self.Message1.configure(width=90)

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.15, rely=0.08, relheight=0.1, relwidth=0.21)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(highlightbackground="wheat")
        self.Frame1.configure(width=125)

        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.12, rely=0.2, relheight=0.3, relwidth=0.56)
        self.Canvas1.configure(background="white")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="wheat")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=330)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.5, rely=0.05, height=31, width=79)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font11)
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Button''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.5, rely=0.1, relheight=0.03, relwidth=0.34)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#b8a786")
        self.Entry1.configure(font=font11)
        self.Entry1.configure(highlightbackground="wheat")
        self.Entry1.configure(selectbackground="#ddc8a1")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.73, rely=0.05, height=23, width=47)
        self.Label1.configure(activebackground="#ffffcd")
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font=font11)
        self.Label1.configure(highlightbackground="wheat")
        self.Label1.configure(text='''Label''')

        self.Listbox1 = Listbox(top)
        self.Listbox1.place(relx=0.12, rely=0.54, relheight=0.26, relwidth=0.34)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#b8a786")
        self.Listbox1.configure(font=font11)
        self.Listbox1.configure(highlightbackground="wheat")
        self.Listbox1.configure(selectbackground="#ddc8a1")

        self.Text1 = Text(top)
        self.Text1.place(relx=0.58, rely=0.52, relheight=0.25, relwidth=0.34)
        self.Text1.configure(background="white")
        self.Text1.configure(font=font11)
        self.Text1.configure(highlightbackground="wheat")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(width=20)
        self.Text1.configure(wrap=WORD)

        self.Checkbutton1 = Checkbutton(top)
        self.Checkbutton1.place(relx=0.73, rely=0.22, relheight=0.03
                , relwidth=0.13)
        self.Checkbutton1.configure(activebackground="#f4bcb2")
        self.Checkbutton1.configure(disabledforeground="#b8a786")
        self.Checkbutton1.configure(font=font11)
        self.Checkbutton1.configure(highlightbackground="wheat")
        self.Checkbutton1.configure(text='''Check''')
        self.Checkbutton1.configure(variable=standard_support.che43)

        self.Radiobutton1 = Radiobutton(top)
        self.Radiobutton1.place(relx=0.77, rely=0.28, relheight=0.03
                , relwidth=0.13)
        self.Radiobutton1.configure(activebackground="#f4bcb2")
        self.Radiobutton1.configure(disabledforeground="#b8a786")
        self.Radiobutton1.configure(font=font11)
        self.Radiobutton1.configure(highlightbackground="wheat")
        self.Radiobutton1.configure(text='''Radio''')

        self.Scale1 = Scale(top)
        self.Scale1.place(relx=0.73, rely=0.38, relwidth=0.17, relheight=0.0
                , height=48)
        self.Scale1.configure(activebackground="#f4bcb2")
        self.Scale1.configure(font=font10)
        self.Scale1.configure(highlightbackground="wheat")
        self.Scale1.configure(orient="horizontal")
        self.Scale1.configure(troughcolor="#d9d9d9")

        self.Spinbox1 = Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.52, rely=0.15, relheight=0.04, relwidth=0.44)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="wheat")
        self.Spinbox1.configure(disabledforeground="#b8a786")
        self.Spinbox1.configure(font=font10)
        self.Spinbox1.configure(from_="1.0")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(textvariable=standard_support.spinbox)
        self.Spinbox1.configure(to="100.0")

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.15, rely=0.84, relheight=0.11
                , relwidth=0.33)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(font=font11)
        self.Labelframe1.configure(text='''Labelframe''')
        self.Labelframe1.configure(highlightbackground="#f5deb3")
        self.Labelframe1.configure(width=195)






if __name__ == '__main__':
    vp_start_gui()



