#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Feb 16, 2017 05:29:59 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import lib_demo_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Library_Demo (root)
    lib_demo_support.init(root, top)
    root.mainloop()

w = None
def create_Library_Demo(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Library_Demo (w)
    lib_demo_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Library_Demo():
    global w
    w.destroy()
    w = None


class Library_Demo:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#f5deb3'  # X11 color: 'wheat'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 
        font10 = "-family {DejaVu Sans} -size 14 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x450+650+150")
        top.title("Library Demo")
        top.configure(background="#f5deb3")
        top.configure(highlightbackground="#f5deb3")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font=font10,bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.zoom = Menu(top,tearoff=0)
        self.menubar.add_cascade(menu=self.zoom,
                activebackground="#f4bcb2",
                activeforeground="#111111",
                background="#f5deb3",
                font=font11,
                foreground="#000000",
                label="Zoom")
        self.zoom.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lambda:lib_demo_support.zoom('in'),
                font=font11,
                foreground="#000000",
                label="Zoom In")
        self.zoom.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lambda:lib_demo_support.zoom('out'),
                font=font11,
                foreground="#000000",
                label="Zoom Out")
        self.zoom.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lambda:lib_demo_support.zoom('default'),
                font=font11,
                foreground="#000000",
                label="Default Size")
        self.menubar.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lib_demo_support.refresh,
                font=font11,
                foreground="#000000",
                label="Refresh")
        self.menubar.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lib_demo_support.quit,
                font=font11,
                foreground="#000000",
                label="Quit")


        self.Custom1 = lib_demo_support.Custom(top)
        self.Custom1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)

    @staticmethod
    def popup1(event):
        font11 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font12 = "-family {DejaVu Sans} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans Mono} -size 14 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        Popupmenu1 = Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ffffcd")
        Popupmenu1.configure(background="#f5deb3")
        Popupmenu1.configure(disabledforeground="#b8a786")
        Popupmenu1.configure(font=font12)
        zoom = Menu(Popupmenu1,tearoff=0)
        Popupmenu1.add_cascade(menu=zoom,
                activebackground="#f4bcb2",
                activeforeground="#111111",
                background="#f5deb3",
                font=font9,
                foreground="#000000",
                label="Zoom")
        zoom.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lambda:lib_demo_support.zoom('in'),
                font=font11,
                foreground="#000000",
                label="Zoom In")
        zoom.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lambda:lib_demo_support.zoom('out'),
                font=font11,
                foreground="#000000",
                label="Zoom Out")
        zoom.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lambda:lib_demo_support.zoom('default'),
                font=font11,
                foreground="#000000",
                label="Default Size")
        Popupmenu1.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lib_demo_support.refresh,
                font=font11,
                foreground="#000000",
                label="Refresh")
        Popupmenu1.add_command(
                activebackground="#f4bcb2",
                activeforeground="#000000",
                background="#f5deb3",
                command=lib_demo_support.quit,
                font=font11,
                foreground="#000000",
                label="Quit")
        Popupmenu1.post(event.x_root, event.y_root)






if __name__ == '__main__':
    vp_start_gui()



