#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.5
# In conjunction with Tcl version 8.6
#    Nov 07, 2016 06:03:41 PM
#    Nov 07, 2016 06:11:50 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1





def quit():
    print('bind_example_support.quit')
    sys.stdout.flush()
    sys.exit()


def button_handler1():
    print('bind_example_support.button_handler1')
    print('Mouse button 1')
    sys.stdout.flush()

def button_handler2(p1,p2):
    print('bind_example_support.button_handler2')
    print('Mouse button %d' % p2)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import bind_example
    bind_example.vp_start_gui()





