#############################################################################
# Generated by PAGE version 4.8.9.3
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #f5deb3
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #f5deb3
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tPa38.p1 
    set site_4_1 .top37.tPa38.p2 
    set site_4_0 $site_4_1
    set site_6_0 .top37.tPa38.p2.tPa39.p1 
    set site_6_1 .top37.tPa38.p2.tPa39.p2 
    set site_6_0 $site_6_1
    set site_8_0 .top37.tPa38.p2.tPa39.p2.tNo40.t0 
    set site_8_0 $site_8_0
    set site_8_1 .top37.tPa38.p2.tPa39.p2.tNo40.t1 
    set site_8_0 $site_8_1
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#f5deb3} 
    wm focusmodel $top passive
    wm geometry $top 565x513+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Complex Example"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TPanedwindow -background #f5deb3
    ttk::style configure TPanedwindow.Label -background #f5deb3
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font font9
    ttk::panedwindow $top.tPa38 \
        -width 200 -height 200 
    vTcl:DefineAlias "$top.tPa38" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #f5deb3
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font9
    ttk::style configure TLabelframe -background #f5deb3
    ttk::labelframe $top.tPa38.p1 \
        -text {Pane 1} -width 200 -height 75 
    vTcl:DefineAlias "$top.tPa38.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa38.p1
    $top.tPa38 add $top.tPa38.p1 
        
    ttk::style configure TLabelframe.Label -background #f5deb3
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font9
    ttk::style configure TLabelframe -background #f5deb3
    ttk::labelframe $top.tPa38.p2 \
        -text {Pane 2} -width 200 -height 125 
    vTcl:DefineAlias "$top.tPa38.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa38.p2
    ttk::style configure TPanedwindow -background #f5deb3
    ttk::style configure TPanedwindow.Label -background #f5deb3
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font font9
    ttk::panedwindow $site_4_1.tPa39 \
        -orient horizontal -width 200 -height 200 
    vTcl:DefineAlias "$site_4_1.tPa39" "TPanedwindow2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #f5deb3
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font9
    ttk::style configure TLabelframe -background #f5deb3
    ttk::labelframe $site_4_1.tPa39.p1 \
        -text {Pane 1} -width 85 -height 200 
    vTcl:DefineAlias "$site_4_1.tPa39.p1" "TPanedwindow2_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_4_1.tPa39.p1
    $site_4_1.tPa39 add $site_4_1.tPa39.p1 
        
    ttk::style configure TLabelframe.Label -background #f5deb3
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font font9
    ttk::style configure TLabelframe -background #f5deb3
    ttk::labelframe $site_4_1.tPa39.p2 \
        -text {Pane 2} -width 115 -height 200 
    vTcl:DefineAlias "$site_4_1.tPa39.p2" "TPanedwindow2_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_6_1 $site_4_1.tPa39.p2
    ttk::style configure TNotebook -background #f5deb3
    ttk::style configure TNotebook.Tab -background #f5deb3
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font font9
    ttk::style map TNotebook.Tab -background [list disabled #f5deb3 selected #b2c9f4]
    ttk::notebook $site_6_1.tNo40 \
        -width 300 -height 200 -takefocus {} 
    vTcl:DefineAlias "$site_6_1.tNo40" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_6_1.tNo40.t0 \
        -background {#f5deb3} -highlightbackground {#f5deb3} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_6_1.tNo40.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_6_1.tNo40 add .top37.tPa38.p2.tPa39.p2.tNo40.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound none -underline -1 
    set site_8_0  $site_6_1.tNo40.t0
    label $site_8_0.lab46 \
        -background {#f5deb3} -disabledforeground {#b8a786} -font font9 \
        -foreground {#000000} -text {First Page} 
    vTcl:DefineAlias "$site_8_0.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_8_0.but47 \
        -activebackground {#f4bcb2} -background {#f5deb3} -command qqq \
        -disabledforeground {#b8a786} -font font9 -foreground {#000000} \
        -highlightbackground {#f5deb3} -highlightcolor black -text Redo 
    vTcl:DefineAlias "$site_8_0.but47" "Button2" vTcl:WidgetProc "Toplevel1" 1
    place $site_8_0.lab46 \
        -in $site_8_0 -x 40 -y 40 -anchor nw -bordermode ignore 
    place $site_8_0.but47 \
        -in $site_8_0 -x 110 -y 100 -anchor nw -bordermode ignore 
    frame $site_6_1.tNo40.t1 \
        -background {#f5deb3} -highlightbackground {#f5deb3} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_6_1.tNo40.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $site_6_1.tNo40 add .top37.tPa38.p2.tPa39.p2.tNo40.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound none -underline -1 
    set site_8_1  $site_6_1.tNo40.t1
    message $site_8_1.mes45 \
        -background {#f5deb3} -font font9 -foreground {#000000} \
        -highlightbackground {#f5deb3} -highlightcolor black \
        -text {Second Page} -width 157 
    vTcl:DefineAlias "$site_8_1.mes45" "Message1" vTcl:WidgetProc "Toplevel1" 1
    place $site_8_1.mes45 \
        -in $site_8_1 -x 70 -y 60 -width 157 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_1.tNo40 \
        -in $site_6_1 -x 20 -y 30 -anchor nw -bordermode ignore 
    $site_4_1.tPa39 add $site_4_1.tPa39.p2 
        
    place $site_4_1.tPa39 \
        -in $site_4_1 -x 40 -y 30 -width 430 -relwidth 0 -height 280 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa38 add $top.tPa38.p2 
        
    ttk::style configure TSizegrip -background #f5deb3
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi43 \
        -cursor bottom_right_corner 
    vTcl:DefineAlias "$top.tSi43" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but44 \
        -activebackground {#f4bcb2} -background {#f5deb3} -command quit \
        -disabledforeground {#b8a786} -font font9 -foreground {#000000} \
        -highlightbackground {#f5deb3} -highlightcolor black -text Quit 
    vTcl:DefineAlias "$top.but44" "Button1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa38 \
        -in $top -x 30 -y 30 -width 500 -relwidth 0 -height 410 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSi43 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 
    place $top.but44 \
        -in $top -x 250 -y 460 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

