#############################################################################
# Generated by PAGE version 4.8
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font5
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font6
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top32
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top32 {base} {
    if {$base == ""} {
        set base .top32
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background wheat -highlightbackground wheat -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+918+173
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Main"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Button -background wheat
    ttk::style configure Button -foreground #000000
    ttk::style configure Button -font font1
    button $top.but33 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -command advance -disabledforeground {#b8a786} \
        -font $::vTcl(fonts,vTcl:font6,object) -foreground black \
        -highlightbackground wheat -highlightcolor black \
        -text {Advance Progress Bar} 
    vTcl:DefineAlias "$top.but33" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but34 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -command quit -disabledforeground {#b8a786} \
        -font $::vTcl(fonts,vTcl:font5,object) -foreground black \
        -highlightbackground wheat -highlightcolor black -text Quit 
    vTcl:DefineAlias "$top.but34" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab36 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#b8a786} -font $::vTcl(fonts,vTcl:font5,object) \
        -foreground black -highlightbackground wheat -highlightcolor black \
        -text {Example of Using a Progress bar} 
    vTcl:DefineAlias "$top.lab36" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but33 \
        -in $top -x 180 -y 180 -anchor nw -bordermode ignore 
    place $top.but34 \
        -in $top -x 270 -y 300 -anchor nw -bordermode ignore 
    place $top.lab36 \
        -in $top -x 140 -y 80 -width 352 -height 49 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top32

