#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.9.3
# In conjunction with Tcl version 8.6
#    Apr 10, 2017 06:19:31 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import w1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Window_I (root)
    w1_support.init(root, top)
    root.mainloop()

w = None
def create_Window_I(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Window_I (w)
    w1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Window_I():
    global w
    w.destroy()
    w = None


class Window_I:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#f5deb3'  # X11 color: 'wheat'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
        font9 = "-family {DejaVu Sans} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x450+650+150")
        top.title("Window I")
        top.configure(background="#f5deb3")
        top.configure(highlightbackground="#f5deb3")
        top.configure(highlightcolor="black")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.45, rely=0.51, height=35, width=65)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background="#f5deb3")
        self.Button1.configure(command=w1_support.quit)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font9)
        self.Button1.configure(highlightbackground="#f5deb3")
        self.Button1.configure(text='''Quit''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.43, rely=0.22, height=35, width=166)
        self.Button2.configure(activebackground="#f4bcb2")
        self.Button2.configure(background="#f5deb3")
        self.Button2.configure(command=w1_support.start2)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font=font9)
        self.Button2.configure(highlightbackground="#f5deb3")
        self.Button2.configure(text='''Create Window''')






if __name__ == '__main__':
    vp_start_gui()



