#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.9.3
# In conjunction with Tcl version 8.6
#    Apr 15, 2017 09:23:28 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import w2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    w2_support.set_Tk_var()
    top = Window_II (root)
    w2_support.init(root, top)
    root.mainloop()

w = None
def create_Window_II(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w2_support.set_Tk_var()
    top = Window_II (w)
    w2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Window_II():
    global w
    w.destroy()
    w = None


class Window_II:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#f5deb3'  # X11 color: 'wheat'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 
        font9 = "-family {DejaVu Sans Mono} -size 14 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font=font9)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+123+415")
        top.title("Window II")
        top.configure(background="#f5deb3")
        top.configure(highlightbackground="#f5deb3")
        top.configure(highlightcolor="black")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.48, rely=0.4, height=35, width=81)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background="#f5deb3")
        self.Button1.configure(command=w2_support.close)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font9)
        self.Button1.configure(highlightbackground="#f5deb3")
        self.Button1.configure(text='''Close''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.27, rely=0.18, height=27, width=92)
        self.Label1.configure(activebackground="#ffffcd")
        self.Label1.configure(background="#f5deb3")
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font=font9)
        self.Label1.configure(highlightbackground="#f5deb3")
        self.Label1.configure(text='''Greeting''')
        self.Label1.configure(textvariable=w2_support.greeting)

        self.TProgressbar1 = ttk.Progressbar(top)
        self.TProgressbar1.place(relx=0.27, rely=0.69, relwidth=0.17
                , relheight=0.0, height=19)
        self.TProgressbar1.configure(variable=w2_support.t)






if __name__ == '__main__':
    vp_start_gui()



