#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.7a
# In conjunction with Tcl version 8.6
#    Jan 16, 2017 03:34:10 PM
#    Jan 16, 2017 03:54:39 PM
#    Apr 15, 2017 09:22:23 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global t
    t = IntVar()
    global greeting
    greeting = StringVar()

import time

def close():
    print('w2_support.close')
    sys.stdout.flush()
    greeting.set('Goodbye')
    for i in reversed(range(10)):
        j = i * 10
        t.set(j)
        top_level.update()
        time.sleep(0.1)
    destroy_window()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    greeting.set(args[0])
    t.set(100)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import w2
    w2.vp_start_gui()








