#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.7a
# In conjunction with Tcl version 8.6
#    Jan 16, 2017 06:48:31 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import cal_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Calendar (root)
    cal_support.init(root, top)
    root.mainloop()

w = None
def create_Calendar(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Calendar (w)
    cal_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Calendar():
    global w
    w.destroy()
    w = None


class Calendar:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
        _ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}' 
        _ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2' 
        font11 = "-family {Courier 10 Pitch} -size 14 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font12 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("236x263+1242+211")
        top.title("Calendar")
        top.configure(background="wheat")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")



        self.Text1 = Text(top)
        self.Text1.place(relx=0.0, rely=0.0, relheight=0.71, relwidth=1.0)
        self.Text1.configure(background="white")
        self.Text1.configure(font=font11)
        self.Text1.configure(highlightbackground="wheat")
        self.Text1.configure(selectbackground="#ddc8a1")
        self.Text1.configure(width=236)
        self.Text1.configure(wrap=WORD)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.0, rely=0.72, height=31, width=59)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(background="wheat")
        self.Button1.configure(command=cal_support.last)
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font12)
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(text='''Last''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.3, rely=0.72, height=31, width=87)
        self.Button2.configure(activebackground="#f4bcb2")
        self.Button2.configure(background="wheat")
        self.Button2.configure(command=cal_support.current)
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font=font12)
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(text='''Current''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.72, rely=0.72, height=31, width=63)
        self.Button3.configure(activebackground="#f4bcb2")
        self.Button3.configure(background="wheat")
        self.Button3.configure(command=cal_support.next)
        self.Button3.configure(disabledforeground="#b8a786")
        self.Button3.configure(font=font12)
        self.Button3.configure(highlightbackground="wheat")
        self.Button3.configure(text='''Next''')

        self.Button4 = Button(top)
        self.Button4.place(relx=0.04, rely=0.87, height=30, width=214)
        self.Button4.configure(activebackground="#f4bcb2")
        self.Button4.configure(background="wheat")
        self.Button4.configure(command=cal_support.quit)
        self.Button4.configure(disabledforeground="#b8a786")
        self.Button4.configure(font=font12)
        self.Button4.configure(highlightbackground="wheat")
        self.Button4.configure(text='''Quit''')






if __name__ == '__main__':
    vp_start_gui()



